name: build

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  release:
    types:
      - published

jobs:
  prepare:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        centos-version: [centos6, centos7, centos8]
    steps:
      - uses: actions/checkout@v2
        name: checkout repository
      - name: update dockerfile
        run: sed docker/Dockerfile -e "s/{{centos-version}}/${{ matrix.centos-version }}/" -i
      - name: make docker buildimage
        uses: elgohr/Publish-Docker-Github-Action@master
        with:
          username: "${{ secrets.DOCKER_USERNAME }}"
          password: "${{ secrets.DOCKER_PASSWORD }}"
          name: metwork/mfutilc-${{ matrix.centos-version }}-buildimage
          context: docker
          cache: true
          tags: "latest"
  build:
    runs-on: ubuntu-latest
    needs: prepare
    strategy:
      matrix:
        centos-version: [centos6, centos7, centos8]
    steps:
      - name: checkout repository
        uses: actions/checkout@v2
      - name: debug env
        run: env |grep GITHUB
      - name: build centos6
        if: matrix.centos-version == 'centos6'
        uses: docker://metwork/mfutilc-centos6-buildimage
      - name: build centos7
        if: matrix.centos-version == 'centos7'
        uses: docker://metwork/mfutilc-centos7-buildimage
      - name: build centos8
        if: matrix.centos-version == 'centos8'
        uses: docker://metwork/mfutilc-centos8-buildimage
      - name: compute tag name
        id: vars
        run: |
          TMPREF=${GITHUB_REF#refs/*/}
          if [[ "$TMPREF" == */merge ]]; then echo ::set-output name=tag::`echo pr${TMPREF} |awk -F '/' '{print $1;}'`; else echo ::set-output name=tag::${TMPREF}; fi
      - name: make tar.gz
        if: matrix.centos-version == 'centos6'
        run: |
          ls -l release/*
          mv release mfutil_c-linux64-${{ steps.vars.outputs.tag }}
          tar -cvf mfutil_c-linux64-${{ steps.vars.outputs.tag }}.tar mfutil_c-linux64-${{ steps.vars.outputs.tag }}
          gzip mfutil_c-linux64-${{ steps.vars.outputs.tag }}.tar
      - name: upload artifact
        if: matrix.centos-version == 'centos6'
        uses: actions/upload-artifact@v1
        with:
          name: mfutil_c-linux64-${{ matrix.centos-version }}-${{ steps.vars.outputs.tag }}
          path: ./mfutil_c-linux64-${{ steps.vars.outputs.tag }}
      - name: upload release asset
        id: upload-release-asset
        if: startsWith(github.ref, 'refs/tags/v') && matrix.centos-version == 'centos6'
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: ./mfutil_c-linux64-${{ steps.vars.outputs.tag }}.tar.gz
          asset_name: mfutil_c-linux64-${{ steps.vars.outputs.tag }}.tar.gz
          asset_content_type: application/gzip
