name: CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  release:
    types:
      - published

jobs:
  prepare:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        rocky-number: [8, 9]
    steps:
      - uses: actions/checkout@v3
        name: checkout repository
      - name: update dockerfile
        run: sed docker/Dockerfile -e "s/{{rocky-number}}/${{ matrix.rocky-number }}/" -i
      - name: make docker buildimage
        uses: elgohr/Publish-Docker-Github-Action@v5
        with:
          username: "${{ secrets.DOCKER_USERNAME }}"
          password: "${{ secrets.DOCKER_PASSWORD }}"
          name: metwork/mfutilc-rocky${{ matrix.rocky-number }}-buildimage
          context: docker
          cache: true
          tags: "latest"
  build:
    runs-on: ubuntu-latest
    needs: prepare
    strategy:
      matrix:
        rocky-version: [rocky8, rocky9]
    steps:
      - name: checkout repository
        uses: actions/checkout@v3
      - name: debug env
        run: env |grep GITHUB
      - name: build rocky
        uses: docker://metwork/mfutilc-${{ matrix.rocky-version }-buildimage
      - name: compute tag name
        id: vars
        run: |
          TMPREF=${GITHUB_REF#refs/*/}
          if [[ "$TMPREF" == */merge ]]; then echo "tag="`echo pr${TMPREF} |awk -F '/' '{print $1;}'`>> ${GITHUB_OUTPUT}; else echo "tag="${TMPREF}>> ${GITHUB_OUTPUT}; fi
      - name: make tar.gz
        if: matrix.rocky-version == 'rocky8'
        run: |
          ls -l release/*
          mv release mfutil_c-linux64-${{ steps.vars.outputs.tag }}
          tar -cvf mfutil_c-linux64-${{ steps.vars.outputs.tag }}.tar mfutil_c-linux64-${{ steps.vars.outputs.tag }}
          gzip mfutil_c-linux64-${{ steps.vars.outputs.tag }}.tar
      - name: upload artifact
        if: matrix.rocky-version == 'rocky8'
        uses: actions/upload-artifact@v1
        with:
          name: mfutil_c-linux64-${{ matrix.rocky-version }}-${{ steps.vars.outputs.tag }}
          path: ./mfutil_c-linux64-${{ steps.vars.outputs.tag }}
      - name: upload release asset
        id: upload-release-asset
        if: startsWith(github.ref, 'refs/tags/v') && matrix.rocky-version == '8'
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: ./mfutil_c-linux64-${{ steps.vars.outputs.tag }}.tar.gz
          asset_name: mfutil_c-linux64-${{ steps.vars.outputs.tag }}.tar.gz
          asset_content_type: application/gzip
